name: Test example CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: test hello world
      run: | 
        cd src/1-helloworld 
        docker run -it -v `pwd`/:/src/ ghcr.io/eunomia-bpf/ecc-`uname -m`:latest
        wget https://aka.pw/bpf-ecli -O ecli && chmod +x ./ecli 
        sudo timeout -s 2 3 ./ecli run ./package.json || if [ $? = 124 ]; then exit 0; else exit $?; fi
    - name: install deps
      run: |
        sudo apt-get install -y --no-install-recommends \
        libelf1 libelf-dev zlib1g-dev libclang-13-dev \
        make git clang llvm pkg-config build-essential
